name: Java CI

on:
  push:
    branches: 
      - main
      - master  
  pull_request:
    branches: 
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Navigate to Project Directory
      run: cd my-app  # Change this to match your folder name

    - name: Build with Maven
      run: mvn clean install
      working-directory: my-app  # Set working directory to the folder containing pom.xml

    - name: Run Tests
      run: mvn test
      working-directory: my-app  # Ensure tests also run in the correct folder




